### ISSUE TITLE
Error: request entity too large

### ISSUE THREAD

**Issue by bonesoul** [atatus/atatus-nodejs#1]
----------------
"Error: request entity too large\n    at Request._callback (/var/www/buharmetre/node_modules/atatus-node/index.js:1:4891)\n    at Request.self.callback (/var/www/buharmetre/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:192:7)\n    at Request.<anonymous> (/var/www/buharmetre/node_modules/request/request.js:1081:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:189:7)\n    at IncomingMessage.<anonymous> (/var/www/buharmetre/node_modules/request/request.js:1001:12)\n    at Object.onceWrapper (events.js:291:19)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:186:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at instrumented (/var/www/buharmetre/node_modules/opbeat/lib/instrumentation/index.js:102:27)\n    at /root/.nvm/versions/node/v7.5.0/lib/node_modules/pm2/node_modules/async-listener/glue.js:188:31\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9) 'Sending metrics to Atatus failed: ' 'metrics' undefined\n"

**Comment by fizerkhan** [comment]
Fixed
