### ISSUE TITLE
Npm audit  | found 6 vulnerabilities (5 moderate, 1 high)

### ISSUE THREAD

**Issue by Oxicode** [atatus/atatus-nodejs#2]
![image](https://user-images.githubusercontent.com/1320709/57562256-c0c49080-7356-11e9-8b0b-ec592e62a9d8.png)
![image](https://user-images.githubusercontent.com/1320709/57562267-cc17bc00-7356-11e9-957f-adcb1e1f53d4.png)
![image](https://user-images.githubusercontent.com/1320709/57562275-d6d25100-7356-11e9-9ca6-01208608518d.png)

**Comment by fizerkhan** [comment]
@Oxicode We are working on new Node.js apm agent which will fix this issues. I will let you know once it is available.

**Comment by fizerkhan** [comment]
@Oxicode Released new nodejs agent.
